In [ ]:
import pandas as pd
import numpy as np

In [ ]:
sales=pd.read_csv('sales.csv')

In [ ]:
sales

         date    product  quantity  price
0  2024-01-01  Product_A      10.0  100.0
1  2024-01-01  Product_B       5.0  200.0
2  2024-01-02  Product_A       8.0  100.0
3  2024-01-02  Product_B       NaN  200.0
4  2024-01-03  Product_A      12.0  100.0
5  2024-01-03  Product_B       3.0  200.0
6  2024-01-04  Product_A       7.0  100.0
7  2024-01-04  Product_B       6.0    NaN
8  2024-01-05  Product_A      11.0  100.0
9  2024-01-05  Product_B       8.0  200.0

In [ ]:
sales['quantity']=sales.groupby('product')['quantity'].transform(lambda x:x.fillna(x.mean()))

In [ ]:
sales

         date    product  quantity  price
0  2024-01-01  Product_A      10.0  100.0
1  2024-01-01  Product_B       5.0  200.0
2  2024-01-02  Product_A       8.0  100.0
3  2024-01-02  Product_B       5.5  200.0
4  2024-01-03  Product_A      12.0  100.0
5  2024-01-03  Product_B       3.0  200.0
6  2024-01-04  Product_A       7.0  100.0
7  2024-01-04  Product_B       6.0    NaN
8  2024-01-05  Product_A      11.0  100.0
9  2024-01-05  Product_B       8.0  200.0

In [ ]:
sales['price']=sales.groupby('product')['price'].transform(lambda x:x.fillna(x.median()))

In [ ]:
sales

         date    product  quantity  price
0  2024-01-01  Product_A      10.0  100.0
1  2024-01-01  Product_B       5.0  200.0
2  2024-01-02  Product_A       8.0  100.0
3  2024-01-02  Product_B       5.5  200.0
4  2024-01-03  Product_A      12.0  100.0
5  2024-01-03  Product_B       3.0  200.0
6  2024-01-04  Product_A       7.0  100.0
7  2024-01-04  Product_B       6.0  200.0
8  2024-01-05  Product_A      11.0  100.0
9  2024-01-05  Product_B       8.0  200.0

In [ ]:
sales['date']=pd.to_datetime(sales['date'])

In [ ]:
sales['month']=sales['date'].dt.month

In [ ]:
sales

        date    product  quantity  price  month
0 2024-01-01  Product_A      10.0  100.0      1
1 2024-01-01  Product_B       5.0  200.0      1
2 2024-01-02  Product_A       8.0  100.0      1
3 2024-01-02  Product_B       5.5  200.0      1
4 2024-01-03  Product_A      12.0  100.0      1
5 2024-01-03  Product_B       3.0  200.0      1
6 2024-01-04  Product_A       7.0  100.0      1
7 2024-01-04  Product_B       6.0  200.0      1
8 2024-01-05  Product_A      11.0  100.0      1
9 2024-01-05  Product_B       8.0  200.0      1

In [ ]:
sales['total sales']=sales['quantity']*sales['price']

In [ ]:
sales

        date    product  quantity  price  month  total sales
0 2024-01-01  Product_A      10.0  100.0      1       1000.0
1 2024-01-01  Product_B       5.0  200.0      1       1000.0
2 2024-01-02  Product_A       8.0  100.0      1        800.0
3 2024-01-02  Product_B       5.5  200.0      1       1100.0
4 2024-01-03  Product_A      12.0  100.0      1       1200.0
5 2024-01-03  Product_B       3.0  200.0      1        600.0
6 2024-01-04  Product_A       7.0  100.0      1        700.0
7 2024-01-04  Product_B       6.0  200.0      1       1200.0
8 2024-01-05  Product_A      11.0  100.0      1       1100.0
9 2024-01-05  Product_B       8.0  200.0      1       1600.0

In [ ]:
sales

        date    product  quantity  price  month  total sales
0 2024-01-01  Product_A      10.0  100.0      1       1000.0
1 2024-01-01  Product_B       5.0  200.0      1       1000.0
2 2024-01-02  Product_A       8.0  100.0      1        800.0
3 2024-01-02  Product_B       5.5  200.0      1       1100.0
4 2024-01-03  Product_A      12.0  100.0      1       1200.0
5 2024-01-03  Product_B       3.0  200.0      1        600.0
6 2024-01-04  Product_A       7.0  100.0      1        700.0
7 2024-01-04  Product_B       6.0  200.0      1       1200.0
8 2024-01-05  Product_A      11.0  100.0      1       1100.0
9 2024-01-05  Product_B       8.0  200.0      1       1600.0

In [ ]:
mean_quantity=np.mean(sales['quantity'])

In [ ]:
median_quantity=np.median(sales['quantity'])

In [ ]:
std_quantity=np.std(sales['quantity'])

In [ ]:
mean_price=np.mean(sales['price'])

In [ ]:
median_price=np.median(sales['price'])

In [ ]:
std_price=np.std(sales['price'])

In [ ]:
print(f'the quantity mean {mean_quantity}, the quantity median {median_quantity}, the quantity_std {std_quantity}')

the quantity mean 7.55, the quantity median 7.5, the quantity_std 2.6874709300753374

In [ ]:
print(f'the price mean {mean_price},  median {median_price}, std {std_price}')

the price mean 150.0,  median 150.0, std 50.0

In [ ]:
grouped=sales.groupby('product').agg({'quantity': 'sum' , 'total sales':'sum'})

In [ ]:
grouped

           quantity  total sales
product
Product_A      48.0       4800.0
Product_B      27.5       5500.0

In [ ]:
Top_selling=sales.loc[sales.groupby('product')['total sales'].idxmax(), ['date','total sales', 'product']]

In [ ]:
Top_selling

        date  total sales    product
4 2024-01-03       1200.0  Product_A
9 2024-01-05       1600.0  Product_B

In [ ]:
Top_selling.to_csv('top_selling.csv',index=False)